"""
gen_table.py — includes R^0 (greedy baseline reward at episode 1)
"""
import zipfile, pickle
import numpy as np

MODELS = ['swin_transformer','edgenext','StarNet','shufflenet',
          'mobilevit','NAFNet','bert','NeRF']
LABELS = ['Swin-T','EdgeNeXt','StarNet','ShuffleNet',
          'MobileViT','NAFNet','BERT','NeRF']

def rolling_max(arr, w=10):
    out = []
    for i in range(len(arr)):
        s = max(0, i - w + 1)
        out.append(max(arr[s:i+1]))
    return np.array(out, dtype=float)

rows = []
for m, lb in zip(MODELS, LABELS):
    with zipfile.ZipFile(f'./res_time/{m}/reward_list.pt') as z:
        with z.open('reward_list/data.pkl') as f:
            r = np.array(list(pickle.load(f)), dtype=float)
    with zipfile.ZipFile(f'./res_time/{m}/time_list.pt') as z:
        with z.open('time_list/data.pkl') as f:
            t = np.array(list(pickle.load(f)), dtype=float)

    rmax      = rolling_max(r, w=10)
    cum_t     = np.cumsum(t)
    ep0_t     = float(t[0])
    mean_t    = float(np.mean(t[1:]))
    R0        = float(r[0])                        # greedy baseline reward
    best_ep0  = int(np.argmax(rmax))
    best_ep   = best_ep0 + 1
    best_r    = float(rmax[best_ep0])
    T_star_s  = float(cum_t[best_ep0])
    T_star_h  = T_star_s / 3600
    Nstar     = (T_star_s * 1000.0) / best_r
    days_es   = Nstar / 86400.0
    T_full_s  = float(cum_t[-1])
    days_full = (T_full_s * 1000.0) / best_r / 86400.0

    rows.append(dict(label=lb, ep0_t=ep0_t, mean_t=mean_t,
                     R0=R0, best_ep=best_ep, best_r=best_r,
                     T_star_h=T_star_h, Nstar_M=Nstar/1e6,
                     days_es=days_es, days_full=days_full))

rows.sort(key=lambda x: x['days_es'])

def rank_col(rows, key, ascending=True):
    vals  = [row[key] for row in rows]
    order = sorted(set(vals), reverse=not ascending)
    return order[0], (order[1] if len(order) > 1 else None)

def fmt(val, best, second, fmt_str):
    s = fmt_str.format(val)
    # if val == best:   return r'\textbf{' + s + '}'
    # if val == second: return r'\underline{' + s + '}'
    return s

best_ep0,  sec_ep0  = rank_col(rows, 'ep0_t',    True)
best_mt,   sec_mt   = rank_col(rows, 'mean_t',   True)
best_R0,   sec_R0   = rank_col(rows, 'R0',       False)
best_rv,   sec_rv   = rank_col(rows, 'best_r',   False)
best_Th,   sec_Th   = rank_col(rows, 'T_star_h', True)
best_Nm,   sec_Nm   = rank_col(rows, 'Nstar_M',  True)
best_des,  sec_des  = rank_col(rows, 'days_es',  True)
best_dful, sec_dful = rank_col(rows, 'days_full',True)

lines = []
lines.append(r'% Auto-generated by gen_table.py — requires booktabs, array')
lines.append(r'')
lines.append(r'\begin{table}[t]')
lines.append(r'\centering')
lines.append(
    r'\caption{\add{DQN compiler training overhead and amortized break-even on RTX\,4090 (bs\,=\,64). '
    r'$t_{0}$: episode\,1 cold-start time (greedy + tile enumeration). '
    r'$\bar{t}$: mean iteration time over episodes\,2--5\,000. '
    r'$R^{0}$: per-inference latency reduction (ms) obtained by the greedy baseline at episode\,1. '
    r'$e^{*}$: first episode reaching peak rolling-max reward $R^{*}$. '
    r'$T^{*}$: cumulative training time to $e^{*}$. '
    r'$N^{*}\!=\!T^{*}[\text{ms}]/R^{*}[\text{ms}]$: break-even inference count. '
    r'$\mathrm{Days}^{\mathrm{es}}$/$\mathrm{Days}^{\mathrm{full}}$: break-even days '
    r'under early stopping at $e^{*}$ / full 5\,000-episode training '
    r'(86\,400 calls/day). '
    r'Early stopping cuts break-even by up to \textbf{97\%} '
    r'(StarNet: 13.7 vs.\ 484.8\,days). '
    r'\textbf{Bold}/\underline{underline}: best/second-best; '
    r'sorted by $\mathrm{Days}^{\mathrm{es}}$.}}'
)
lines.append(r'\label{tab:overhead_breakeven}')
lines.append(r'\small')
lines.append(r'\setlength{\tabcolsep}{4pt}')
lines.append(r'\renewcommand{\arraystretch}{1.20}')
lines.append(r'\begin{tabular}{@{}lrrrrrrrrr@{}}')
lines.append(r'\toprule')
lines.append(
    r'\textbf{Model}'
    r' & {$t_{0}$ (s)}'
    r' & {$\bar{t}$ (s)}'
    r' & {$R^{0}$ (ms)}'
    r' & {$e^{*}$}'
    r' & {$R^{*}$ (ms)}'
    r' & {$T^{*}$ (h)}'
    r' & {$N^{*}$ ($\times10^{6}$)}'
    r' & {$\mathrm{Days}^{\mathrm{es}}$}'
    r' & {$\mathrm{Days}^{\mathrm{full}}$} \\'
)
lines.append(r'\midrule')

for row in rows:
    c_ep0  = fmt(row['ep0_t'],    best_ep0,  sec_ep0,  '{:.1f}')
    c_mt   = fmt(row['mean_t'],   best_mt,   sec_mt,   '{:.2f}')
    c_R0   = fmt(row['R0'],       best_R0,   sec_R0,   '{:.3f}')
    c_r    = fmt(row['best_r'],   best_rv,   sec_rv,   '{:.3f}')
    c_Th   = fmt(row['T_star_h'], best_Th,   sec_Th,   '{:.2f}')
    c_Nm   = fmt(row['Nstar_M'],  best_Nm,   sec_Nm,   '{:.2f}')
    c_des  = fmt(row['days_es'],  best_des,  sec_des,  '{:.1f}')
    c_dful = fmt(row['days_full'],best_dful, sec_dful, '{:.1f}')
    c_ep   = str(row['best_ep'])
    lines.append(
        f"{row['label']:<12s}"
        f' & {c_ep0} & {c_mt} & {c_R0} & {c_ep}'
        f' & {c_r} & {c_Th} & {c_Nm}'
        f' & {c_des} & {c_dful} \\\\'
    )

lines.append(r'\bottomrule')
lines.append(r'\end{tabular}')
lines.append(r'\end{table}')

OUT = './outputs/table_overhead_breakeven.tex'
with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Written: {OUT}')
for line in lines:
    print(line)